"""add initial roles

Revision ID: 76965d9244e3
Revises: 14e75cbf3f9f
Create Date: 2024-10-13 23:18:13.852254

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76965d9244e3"
down_revision: Union[str, None] = "14e75cbf3f9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO role (id, name, permissions) VALUES 
        (0, 'admin', '{"read": true, "write": true, "delete": true}'),
        (1, 'user', '{"read": true, "write": false, "delete": false}');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM role WHERE name IN ('admin', 'user');
        """
    )
    # ### end Alembic commands ###
